### PR TITLE
Update electron to v12

### PR DESCRIPTION
**Pull request by ZiBuYuCHN**
* electron version  v11.0.0 -> v12.0.5
* develop open devtools

### CODE REVIEW

**Comment by ZiBuYuCHN** [comment]
Try to commit to a new branch， but just master.

**Comment by MangoTsing** [comment]
> Try to commit to a new branch， but just master.

I create a new branch `electron-12.x`, you can submit merge request to this branch.

Before I encountered some problems during the electron-12.x upgrade, I will see if the upgrade works normally later.

**Comment by ZiBuYuCHN** [comment]
> > Try to commit to a new branch， but just master.
> 
> I create a new branch `electron-12.x`, you can submit merge request to this branch.
> 
> Before I encountered some problems during the electron-12.x upgrade, I will see if the upgrade works normally later.

ok, I will commit to electron-12.x branch. And then, I will commit a new branch about `.vue` with `<script lang="ts">`. I think it can be used in both electron-v11 and electron-v12, so I call this branch is `vue2ts`.

**Comment by MangoTsing** [comment]
Merged #16

**Pull request closed without merging**
